export class SaleProductModel {
    _id: string = '';
    sale_id: string = '';
    product_id: string = '';
    variant_id: string = '';
    product_name: string = '';
    variant_name: string = '';
    price: number = 0;
    qty: number = 0;
    sign: number = 0;
    tax: number = 0;
    discount_mode: string = '';
    discount_value: number = 0;
    note: string = '';
    blank_cup_weight: number = 0;
    serial_number: string = '';
    weight: number = 0;
    voided: number = 0;
}
